# Drone analysis

File obtained on March 30 from:

https://github.com/voxmedia/data-projects/blob/master/verge-drones-over-america/drone-data-full.csv

In [54]:
import pandas as pd 

dexemptions = pd.read_csv("data/exemptions/drone-data-full.csv")

## Uncomment to check
#dexemptions.head()
dexemptions[dexemptions["location"] == "CT"]

,date,company,category,various_applications,aircraft,location
163,4/17/2015,Photo-Flight Aerial Media,"Photo/Film, Real Estate",False,DJI Phantom 2 Vision+,CT
263,5/5/2015,"The Travelers Companies, Inc","Education, Construction",False,"3DRobotics IRIS+, DJI Phantom 2, DJI Phantom 3...",CT
264,5/5/2015,C.E.T Aviation,Photo/Film,False,"DJI Flame Wheel F550, Zeta Science Buffalo FX-79",CT
265,5/5/2015,"The Travelers Companies, Inc",Emergency Services,False,"3DR IRIS+, DJI Phantom 2",CT
287,5/8/2015,"Pete's Precision Photo, LLC",Photo/Film,False,"DJI Phantom 2 Vision, DJI Phantom 2 Vision+",CT
306,5/11/2015,Joshua A. Strunk,"Real Estate, Research",False,DJI Phantom 2 Vision+,CT
513,6/5/2015,The Scene Lab LLC,Real Estate,False,DJI Phantom Vision 2+,CT
555,6/9/2015,"James Baldwin, Jr. dba SkyVideoCT","Photo/Film, Real Estate",False,DJI Inspire 1,CT
563,6/12/2015,Kyle Norton,Real Estate,False,"DJI Phantom 2 Vision+, DJI Phantom 3",CT
609,6/17/2015,Sky Eye LLC,"Photo/Film, Construction, Real Estate",False,"DJI Phantom 3, DJI Phantom 2 Vision+, DJI Insp...",CT
630,6/23/2015,Pinncal X LLC,"Manufacturer, Emergency Serivices, Utilities/E...",True,Pinnacl X Chameleon Pro,CT
861,7/24/2015,Enda Cusack,Real Estate,False,DJI Inspire 1,CT
937,7/29/2015,Faris Enterprises LLC dba Eastern Drones,Real Estate,False,Yuneec Q500 Typhoon,CT
966,7/31/2015,Marcott Studios,"Photo/Film, Real Estate",False,DJI Phantom 3,CT
1244,8/20/2015,Mohawk Northeast Inc,Construction,False,"3D Robotics Iris+, DJI Phantom 2 Vision+",CT
1274,8/24/2015,Drone View Aerial Photo,Photo/Film,False,DJI Phantom 3,CT
1275,8/24/2015,Griffin Aerial LLC,"Agriculture, Utilities/Energy/Infrastructure, ...",True,"DJI S900, DJI S1000, 3D Robotics Iris +, 3D Ro...",CT
1320,8/26/2015,Peter Sachs Esq,Photo/Film,False,Tailor Toys PowerUp 3.0,CT
1380,9/1/2015,Justin Mashuta,Real Estate,False,DJI Phantom 3 Professional,CT
1640,9/22/2015,Eagle Eye Photo Imaging,Photo/Film,False,DJI Phantom 3 Professional,CT
1654,9/24/2015,Stonewater Photo,Real Estate,False,"DJI Phantom 2 Vision+, DJI Inspire 1",CT
2129,11/5/2015,Delaney Productions,"Real Estate, Photo/Film, Research and Development",False,DJI Phantom 2,CT
2225,11/16/2015,Holland Engineering,Construction,False,Aibotix X6,CT
2257,11/17/2015,Skypics LLC,"Real Estate, Emergency Services",False,"DJI Inspire 1, DJI Phantom Vision 2, Turbo Ace...",CT
2603,12/17/2015,iSKY Aviation and Maritime Solution LLC,"Photo/Film, Utilities/Energy/Infrastructure",False,DJI Phantom 2 Vision+,CT

## Number of drone exemptions per state

In [49]:
dexemptions["location"].value_counts()

FL                                           306
CA                                           305
TX                                           234
CO                                            89
IL                                            89
VA                                            84
OH                                            81
NC                                            80
PA                                            79
AZ                                            78
WA                                            77
MI                                            73
NY                                            71
GA                                            70
NJ                                            56
IN                                            54
MD                                            51
MN                                            48
TN                                            48
LA                                            47
OR                                            46
MA                                            42
OK                                            41
NV                                            39
SC                                            37
KY                                            36
WI                                            35
MO                                            35
IA                                            33
AL                                            29
                                            ...
AK                                            16
NE                                            16
NH                                            15
WV                                            12
WY                                            12
PR                                            12
NM                                            12
MS                                             9
SD                                             9
ND                                             9
AR                                             7
VT                                             6
RI                                             5
Canada                                         5
DC                                             5
DE                                             4
AK                                             3
Austria                                        1
Switzerland                                    1
Corvallis                                      1
Australia                                      1
KA                                             1
San                                            1
                                               1
Alberta, Canada                                1
Oaks                                           1
20506 West Slater Road, Trivoli, IL 61569      1
Las                                            1
E                                              1
NB                                             1
Name: location, dtype: int64

## Drones in CT

#### Total count

In [63]:
ctexemptions = dexemptions[dexemptions["location"] == "CT"]
ctexemptions["location"].value_counts()

CT    25
Name: location, dtype: int64

#### By category

In [64]:
ctexemptions["category"].value_counts()

Real Estate                                                                             6
Photo/Film                                                                              5
Photo/Film, Real Estate                                                                 3
Construction                                                                            2
Real Estate, Photo/Film, Research and Development                                       1
Real Estate, Emergency Services                                                         1
Education, Construction                                                                 1
Manufacturer, Emergency Serivices, Utilities/Energy/Infrastructure                      1
Photo/Film, Construction, Real Estate                                                   1
Emergency Services                                                                      1
Real Estate, Research                                                                   1
Agriculture, Utilities/Energy/Infrastructure, Photo/Film, Construction, Conservation    1
Photo/Film, Utilities/Energy/Infrastructure                                             1
Name: category, dtype: int64

In [65]:
ctexemptions[["company","category"]]

,company,category
163,Photo-Flight Aerial Media,"Photo/Film, Real Estate"
263,"The Travelers Companies, Inc","Education, Construction"
264,C.E.T Aviation,Photo/Film
265,"The Travelers Companies, Inc",Emergency Services
287,"Pete's Precision Photo, LLC",Photo/Film
306,Joshua A. Strunk,"Real Estate, Research"
513,The Scene Lab LLC,Real Estate
555,"James Baldwin, Jr. dba SkyVideoCT","Photo/Film, Real Estate"
563,Kyle Norton,Real Estate
609,Sky Eye LLC,"Photo/Film, Construction, Real Estate"
630,Pinncal X LLC,"Manufacturer, Emergency Serivices, Utilities/E..."
861,Enda Cusack,Real Estate
937,Faris Enterprises LLC dba Eastern Drones,Real Estate
966,Marcott Studios,"Photo/Film, Real Estate"
1244,Mohawk Northeast Inc,Construction
1274,Drone View Aerial Photo,Photo/Film
1275,Griffin Aerial LLC,"Agriculture, Utilities/Energy/Infrastructure, ..."
1320,Peter Sachs Esq,Photo/Film
1380,Justin Mashuta,Real Estate
1640,Eagle Eye Photo Imaging,Photo/Film
1654,Stonewater Photo,Real Estate
2129,Delaney Productions,"Real Estate, Photo/Film, Research and Development"
2225,Holland Engineering,Construction
2257,Skypics LLC,"Real Estate, Emergency Services"
2603,iSKY Aviation and Maritime Solution LLC,"Photo/Film, Utilities/Energy/Infrastructure"

In [127]:
## Count categories
ctexemptions["category"].value_counts()

Real Estate                                                                             6
Photo/Film                                                                              5
Photo/Film, Real Estate                                                                 3
Construction                                                                            2
Real Estate, Photo/Film, Research and Development                                       1
Real Estate, Emergency Services                                                         1
Education, Construction                                                                 1
Manufacturer, Emergency Serivices, Utilities/Energy/Infrastructure                      1
Photo/Film, Construction, Real Estate                                                   1
Emergency Services                                                                      1
Real Estate, Research                                                                   1
Agriculture, Utilities/Energy/Infrastructure, Photo/Film, Construction, Conservation    1
Photo/Film, Utilities/Energy/Infrastructure                                             1
Name: category, dtype: int64

In [130]:
## Count how many exemptions are for multiple use categories

ctexemptions[ctexemptions["category"].str.contains(",", case=False)]["category"].count()

11

In [182]:
## Count categories better
## Since the categories are comma-separated lists, let's explode

## turn a column of comma-separated lists into a list of discrete values
def discrete_values (col):
    categories = []
    map(lambda x : (map(lambda y : categories.append(y.strip().lower()), x.split(","))), col)
    disc = pd.Series(categories).to_frame()[0].value_counts().to_frame()
    disc.reset_index(level=0, inplace=True)
    disc.columns=["category","count"]
    return disc
             
discrete_values(ctexemptions["category"])

## Variable for discrete categories
#categories = []
#map(lambda x : (map(lambda y : categories.append(y.strip().lower()), x.split(","))), ctexemptions["category"])

#discrete_categories = pd.Series(categories).to_frame()[0].value_counts().to_frame()
#discrete_categories.reset_index(level=0, inplace=True)
#discrete_categories.columns=["category","exemptions"]
                             
#discrete_categories

                           category  count
0                       real estate     13
1                        photo/film     12
2                      construction      5
3   utilities/energy/infrastructure      3
4                emergency services      2
5          research and development      1
6                          research      1
7               emergency serivices      1
8                         education      1
9                       agriculture      1
10                     manufacturer      1
11                     conservation      1

In [183]:
## generate an html list of the discrete categories

def categories_report (df):
    report_string = ""
    for row in (df).iterrows():
        report_string += str(row[1][0]).title() + " (" + str(row[1][1]) + "); "
    return report_string
categories_report(discrete_categories)

'Real Estate (13); Photo/Film (12); Construction (5); Utilities/Energy/Infrastructure (3); Emergency Services (2); Research And Development (1); Research (1); Emergency Serivices (1); Education (1); Agriculture (1); Manufacturer (1); Conservation (1); '

In [184]:
## How many contain the term "real estate" (case inensitive)

ctexemptions[ctexemptions["category"].str.contains("real", case=False)]["category"].value_counts()

Real Estate                                          6
Photo/Film, Real Estate                              3
Real Estate, Emergency Services                      1
Real Estate, Photo/Film, Research and Development    1
Real Estate, Research                                1
Photo/Film, Construction, Real Estate                1
Name: category, dtype: int64

In [185]:
ctexemptions [ctexemptions["category"].str.contains("estate", case=False)]["category"].value_counts()

Real Estate                                          6
Photo/Film, Real Estate                              3
Real Estate, Emergency Services                      1
Real Estate, Photo/Film, Research and Development    1
Real Estate, Research                                1
Photo/Film, Construction, Real Estate                1
Name: category, dtype: int64

#### Conclusion:

Real estate, presumably for photographing properties, is a common application of drones

In [186]:
ctexemptions [ctexemptions["category"].str.contains("real", case=False)]["category"].value_counts()

Real Estate                                          6
Photo/Film, Real Estate                              3
Real Estate, Emergency Services                      1
Real Estate, Photo/Film, Research and Development    1
Real Estate, Research                                1
Photo/Film, Construction, Real Estate                1
Name: category, dtype: int64

In [192]:
## Types of drones

discrete_values(ctexemptions["aircraft"])

                      category  count
0        dji phantom 2 vision+      8
1                dji phantom 3      5
2                dji inspire 1      5
3                dji phantom 2      3
4   dji phantom 3 professional      2
5             3d robotics solo      2
6                   aibotix x6      1
7           turbo ace matrix s      1
8         dji flame wheel f550      1
9                     dji s900      1
10  zeta science buffalo fx-79      1
11       dji phantom vision 2+      1
12            3drobotics iris+      1
13            3d robotics x8-m      1
14          3d robotics aero-m      1
15        dji phantom vision 2      1
16           3d robotics iris+      1
17          3d robotics iris +      1
18        dji phantom 2 vision      1
19                   dji s1000      1
20     pinnacl x chameleon pro      1
21                   3dr iris+      1
22     tailor toys powerup 3.0      1
23         yuneec q500 typhoon      1

In [196]:
dexemptions[dexemptions["location"] == "CT"][["company","category","aircraft"]]

,company,category,aircraft
163,Photo-Flight Aerial Media,"Photo/Film, Real Estate",DJI Phantom 2 Vision+
263,"The Travelers Companies, Inc","Education, Construction","3DRobotics IRIS+, DJI Phantom 2, DJI Phantom 3..."
264,C.E.T Aviation,Photo/Film,"DJI Flame Wheel F550, Zeta Science Buffalo FX-79"
265,"The Travelers Companies, Inc",Emergency Services,"3DR IRIS+, DJI Phantom 2"
287,"Pete's Precision Photo, LLC",Photo/Film,"DJI Phantom 2 Vision, DJI Phantom 2 Vision+"
306,Joshua A. Strunk,"Real Estate, Research",DJI Phantom 2 Vision+
513,The Scene Lab LLC,Real Estate,DJI Phantom Vision 2+
555,"James Baldwin, Jr. dba SkyVideoCT","Photo/Film, Real Estate",DJI Inspire 1
563,Kyle Norton,Real Estate,"DJI Phantom 2 Vision+, DJI Phantom 3"
609,Sky Eye LLC,"Photo/Film, Construction, Real Estate","DJI Phantom 3, DJI Phantom 2 Vision+, DJI Insp..."
630,Pinncal X LLC,"Manufacturer, Emergency Serivices, Utilities/E...",Pinnacl X Chameleon Pro
861,Enda Cusack,Real Estate,DJI Inspire 1
937,Faris Enterprises LLC dba Eastern Drones,Real Estate,Yuneec Q500 Typhoon
966,Marcott Studios,"Photo/Film, Real Estate",DJI Phantom 3
1244,Mohawk Northeast Inc,Construction,"3D Robotics Iris+, DJI Phantom 2 Vision+"
1274,Drone View Aerial Photo,Photo/Film,DJI Phantom 3
1275,Griffin Aerial LLC,"Agriculture, Utilities/Energy/Infrastructure, ...","DJI S900, DJI S1000, 3D Robotics Iris +, 3D Ro..."
1320,Peter Sachs Esq,Photo/Film,Tailor Toys PowerUp 3.0
1380,Justin Mashuta,Real Estate,DJI Phantom 3 Professional
1640,Eagle Eye Photo Imaging,Photo/Film,DJI Phantom 3 Professional
1654,Stonewater Photo,Real Estate,"DJI Phantom 2 Vision+, DJI Inspire 1"
2129,Delaney Productions,"Real Estate, Photo/Film, Research and Development",DJI Phantom 2
2225,Holland Engineering,Construction,Aibotix X6
2257,Skypics LLC,"Real Estate, Emergency Services","DJI Inspire 1, DJI Phantom Vision 2, Turbo Ace..."
2603,iSKY Aviation and Maritime Solution LLC,"Photo/Film, Utilities/Energy/Infrastructure",DJI Phantom 2 Vision+

In [197]:
dexemptions[dexemptions["company"].str.contains("Holland Engineering")]

,date,company,category,various_applications,aircraft,location
2225,11/16/2015,Holland Engineering,Construction,False,Aibotix X6,CT

In [198]:
dexemptions[dexemptions["company"].str.contains("Travelers")]

,date,company,category,various_applications,aircraft,location
263,5/5/2015,"The Travelers Companies, Inc","Education, Construction",False,"3DRobotics IRIS+, DJI Phantom 2, DJI Phantom 3...",CT
265,5/5/2015,"The Travelers Companies, Inc",Emergency Services,False,"3DR IRIS+, DJI Phantom 2",CT